# Generated by Django 3.0.4 on 2020-04-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Brand')),
                ('enabled', models.IntegerField()),
                ('source_id', models.CharField(max_length=250)),
                ('wait_list', models.IntegerField()),
                ('is_recommended', models.IntegerField()),
                ('sort_index', models.IntegerField()),
                ('source_type', models.CharField(max_length=250)),
                ('gallery_attribute', models.CharField(max_length=250)),
                ('gallery_name', models.CharField(max_length=250)),
                ('kind', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
