# Generated by Django 3.0.5 on 2020-04-28 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='full_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='full_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='full_text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='intro_text_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='intro_text_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='intro_text_uk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_description_uk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_keyword_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_keyword_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_keyword_uk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_title_uk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='alias',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='content',
            name='geo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='intro_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='meta_tag_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='meta_tag_keyword',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='meta_tag_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crosserrorstatistic',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torsion_shop.Review'),
        ),
        migrations.AlterField(
            model_name='runstring',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userrequesttype',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
