# Generated by Django 3.0.5 on 2020-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='full_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='intro_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='intro_text_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='intro_text_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='intro_text_uk',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/main_image/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='published',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_uk',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
