# Generated by Django 3.0.5 on 2020-04-28 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0002_auto_20200428_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='main_image',
            field=models.ImageField(upload_to='content/main_image/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
