# Generated by Django 3.0.5 on 2020-05-05 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0002_auto_20200505_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='income_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
