# Generated by Django 3.0.5 on 2020-04-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0004_auto_20200429_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='alias',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
