# Generated by Django 3.0.5 on 2020-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torsion_shop', '0005_auto_20200426_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcategory',
            options={'verbose_name': 'CatalogCategory', 'verbose_name_plural': 'CatalogCategories'},
        ),
        migrations.AlterModelOptions(
            name='catalogcategorylang',
            options={'verbose_name': 'CatalogCategoryLang', 'verbose_name_plural': 'CatalogCategoryLangs'},
        ),
        migrations.AlterModelOptions(
            name='categorylang',
            options={'verbose_name': 'CategoryLang', 'verbose_name_plural': 'CategoryLangs'},
        ),
        migrations.AlterModelOptions(
            name='categorymapping',
            options={'verbose_name': 'CategoryMapping', 'verbose_name_plural': 'CategoryMappings'},
        ),
        migrations.AlterModelOptions(
            name='constant',
            options={'verbose_name': 'Constant', 'verbose_name_plural': 'Constant'},
        ),
        migrations.AlterModelOptions(
            name='contentlang',
            options={'verbose_name': 'ContentLang', 'verbose_name_plural': 'ContentLangs'},
        ),
        migrations.AlterModelOptions(
            name='cross',
            options={'verbose_name': 'Cross', 'verbose_name_plural': 'Crosses'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='content_id',
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='content_id',
            field=models.ManyToManyField(related_name='catalogcategory_content', to='torsion_shop.Content'),
        ),
        migrations.RemoveField(
            model_name='catalogcategorylang',
            name='category_id',
        ),
        migrations.AddField(
            model_name='catalogcategorylang',
            name='category_id',
            field=models.ManyToManyField(related_name='catalogcategorylang_category', to='torsion_shop.Category'),
        ),
        migrations.RemoveField(
            model_name='categorylang',
            name='category_id',
        ),
        migrations.AddField(
            model_name='categorylang',
            name='category_id',
            field=models.ManyToManyField(related_name='categorylang_category', to='torsion_shop.Category'),
        ),
        migrations.RemoveField(
            model_name='categorymapping',
            name='category_id',
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='category_id',
            field=models.ManyToManyField(related_name='categorymapping_category', to='torsion_shop.Category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='main_image',
            field=models.ImageField(upload_to='content/'),
        ),
        migrations.RemoveField(
            model_name='contentlang',
            name='content_id',
        ),
        migrations.AddField(
            model_name='contentlang',
            name='content_id',
            field=models.ManyToManyField(related_name='contentlang_content', to='torsion_shop.Content'),
        ),
        migrations.RemoveField(
            model_name='cross',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cross',
            name='product_id',
            field=models.ManyToManyField(related_name='cross_product', to='torsion_shop.Product'),
        ),
    ]
